
version: "3"

services:

  app:
    build:

      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    working_dir: /app
    command: make start
    volumes:
      - "./app:/app"

  caddy:
    build:

      context: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/caddy:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app
volumes:
  caddy_data:
  caddy_config:
