
version: "3.9"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: nic11371/devops-for-programmers-project-74
    environment:
      POSTGRES_HOST: ${DATABASE_HOST}
      POSTGRES_NAME: ${DATABASE_NAME}
      POSTGRES_USERNAME: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    command: make test
    depends_on:
      - db

  db:
    image: postgres
    volumes:
        - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_HOST}
      POSTGRES_USER: ${DATABASE_USERNAME}

    restart: always

volumes:
    pgdata:
