
version: "3"

services:

  app:
    build:

      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    working_dir: /app
    command: make start
    volumes:
      - "./app:/app"

  caddy:
    build:

      context: .
      dockerfile: services/caddy/Dockerfile

    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
volumes:
  - caddy_data:/data
  - caddy_config:/config
