
version: "3.9"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: nic11371/devops-for-programmers-project-74
    environment:
      POSTGRES_HOST: ${DATABASE_HOST}
      POSTGRES_NAME: ${DATABASE_NAME}
      POSTGRES_USERNAME: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    command: make test
    depends_on:
      - db

  db:
    image: postgres:17.1
    volumes:
        - pgdata:/var/lib/postgresql/data
        - .:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_HOST}
      POSTGRES_USER: ${DATABASE_USERNAME}
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
    pgdata:
