
version: "3"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
    command: make dev

  caddy:
    image: caddy
    depends_on: [app]
    volumes:
      - "./services/caddy/Caddyfile:/etc/caddy/Caddyfile"
    ports:
      - "80:80"
      - "443:443"
volumes:
  caddy_data:
  caddy_config:
