
version: "3.9"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: nic11371/devops-for-programmers-project-74
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_NAME: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    command: make test
    depends_on:
      - db

  db:
    image: postgres
    volumes:
        - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres

    restart: always

volumes:
    pgdata:
