name: push

on:
  push:
    branches: [ "main" ]
env:
  APP_IMAGE_NAME:  nic11371/devops-for-programmers-project-74
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run tests
      run: make ci

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build production app
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile.production
        push: true
        tags: ${{ env.APP_IMAGE_NAME }}:latest
