name: run tests and deploy
on: push
jobs:
  run_postgres:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run PostgreSQL command
        run: psql -U postgres -c 'SELECT * FROM mytable;'
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Run tests
        run: make ci

      - name: Build prod
        run: make ci-build

      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to docker hub
        run: make push