name: push
on: push

env:
  CI: true
  APP_IMAGE_NAME: nic11371/devops-for-programmers-project-74
  DATABASE_NAME: postgres
  DATABASE_USERNAME: postgres
  DATABASE_PASSWORD: postgres
  DATABASE_HOST: db

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Run tests
        run: make ci

      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build App
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.production
          push: true
          tags: ${{ env.APP_IMAGE_NAME }}

      - name: Push to docker hub
        run: make push
